apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: imx11uba4-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/imx11uba4-java-springboot-gitops